### ISSUE TITLE
clang-formatでServer側のコードフォーマットを行いたい

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/hatohol#1203]
問題というよりも近い将来行いたい事でしょうか。

[clang-format](http://clang.llvm.org/docs/ClangFormat.html)を使えばC++のコードでも例えばGo言語にあるようなgo fmtのようなことを自動で行うことが出来ます。

これをうまく使うことができればレビュアーがコードのスタイルを指摘する労力が減り、潜在的な問題を指摘できるようになりそうだと思うのですが、如何でしょうか？

**Comment by kz0817** [comment]
いいね！機械的にできることは、machineにやらせるのがいいですよね。人は考える葦なのだから。

**Comment by cosmo0920** [comment]
前にちょこっとだけ試してみた.clang-formatを貼っておきます。
clang-format-3.5向けです。
一番差分が出ないような設定で作ってみました。
テスト側では試していないのでまだ改良の余地は大いにありそうです。

```yaml
BasedOnStyle: Google
IndentWidth: 8
UseTab: Always
BreakBeforeBraces: Allman
IndentCaseLabels: false
AllowShortFunctionsOnASingleLine: false
AllowShortIfStatementsOnASingleLine: false
ColumnLimit: 0
AlignTrailingComments: true
AccessModifierOffset: -2
ConstructorInitializerIndentWidth: 0
AlignEscapedNewlinesLeft: false
AlwaysBreakBeforeMultilineStrings: false
```
